dwb_controller:
  ros__parameters:
    min_vel_x: 0.05
    max_vel_x: 0.5
    min_vel_theta: -0.2
    max_vel_theta: 0.2
    acc_lim_x: 0.2
    acc_lim_theta: 0.5
    yaw_goal_tolerance: 0.1
    xy_goal_tolerance: 0.5
    prune_plan: true
    use_dwa: false
    sim_time: 10
    sim_granularity: 0.2
    angular_sim_granularity: 0.1
    path_distance_bias: 5.0
    goal_distance_bias: 1.2
