global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      width: 500
      height: 500
      resolution: 0.5
      robot_base_frame: base_link
      global_frame: odom
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
