local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 10.0
      publish_frequency: 5.0
      rolling_window: true
      width: 100.0
      height: 100.0
      resolution: 0.25
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        map_topic: "map"
      obstacle_layer:
        enabled: true
        observation_sources: scan
        scan:
          sensor_frame: base_link
          data_type: LaserScan
          topic: scan
          marking: true
          clearing: true
      inflation_layer:
        inflation_radius: 0.5
