teb_local_planner:
  ros__parameters:
    teb_autosize: true
    max_vel_x: 1.0
    max_vel_theta: 0.4
    acc_lim_x: 0.8
    acc_lim_theta: 0.2
    dt_ref: 0.4
    dt_hysteresis: 0.1
    global_plan_overwrite_orientation: true
    max_global_plan_lookahead_dist: 5.0
