navsat_transform_node:
  ros__parameters:
    broadcast_utm_transform: true
    magnetic_declination_radians: 0.0  # Adjust this based on your location
    yaw_offset: 0.0  # Adjust if your robot's heading needs to be offset from the GPS heading
    use_odometry_yaw: false  # Set to true if you want to use odometry's yaw instead of IMU's
    use_sim_time: true  # Use simulation time; set to false if running on a real robot
    datum: [0.0, 0.0, 0.0]  # Latitude, Longitude, Altitude of the map origin
    subscribe_to_gps: true
    wait_for_datum: false
    map_frame: map  # The frame ID of the map frame
    world_frame: odom  # The frame ID of the world fixed frame
    base_frame: base_link  # The frame ID of the robot base
    broadcast_utm_transform: true  # Whether to broadcast the UTM->Map transform
    zero_altitude: true  # Whether to force the altitude to zero
    publish_filtered_gps: true  # Whether to publish a filtered GPS fix
    gps_topic: /argo_sim/gps/fix  # Topic for receiving GPS data
    imu_topic: /argo_sim/imu/data  # Topic for receiving IMU data
    odom_topic: /argo_sim/odom  # Topic for receiving odometry data (optional)
