# nav2_params.yaml

# Use sim time for simulation purposes
use_sim_time: true

# Global Costmap Configuration
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  use_sim_time: true
  robot_radius: 0.7  # Adjust this to the size of your robot
  resolution: 0.05  # Specify the resolution of the costmap
  static_layer:
    map_topic: /map
  always_send_full_costmap: true

# Global planner parameters
# You can adjust these parameters or add more based on your navigation strategy
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: true
    planner_plugin: "nav2_navfn_planner/NavfnPlanner"
    NavfnPlanner:
      allow_unknown: true

# Controller parameters
# Placeholder for controller settings; adjust as needed
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugin: "dwb_core/DWBLocalPlanner"
    DWBLocalPlanner:
      # Example parameter: adjust the following parameters according to your setup
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      min_speed_theta: 0.0

# Recovery server parameters
# Placeholder for recovery behaviors; adjust as needed
recoveries_server:
  ros__parameters:
    use_sim_time: true
    recovery_plugins: ["spin", "backup", "clear_costmap"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    clear_costmap:
      plugin: "nav2_recoveries/ClearCostmap"
      clear_radius: 2.0
      clear_on_reset: true
